BEGIN;

CREATE TABLE IF NOT EXISTS boards (
    board_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    board_name VARCHAR(40) NOT NULL,
    description VARCHAR(200),
    created_by BIGINT REFERENCES members(member_id),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE boards ADD COLUMN IF NOT EXISTS category VARCHAR(20) NOT NULL DEFAULT '자유';
ALTER TABLE boards ADD COLUMN IF NOT EXISTS creation_reason VARCHAR(500);
ALTER TABLE boards ADD COLUMN IF NOT EXISTS is_default BOOLEAN NOT NULL DEFAULT FALSE;
CREATE UNIQUE INDEX IF NOT EXISTS uq_boards_name_ci ON boards (LOWER(board_name));

INSERT INTO boards (board_name, category, description, created_by, is_default)
SELECT '자유게시판', '자유', '함께 배우고, 편하게 이야기해요.', NULL, TRUE
WHERE NOT EXISTS (SELECT 1 FROM boards WHERE LOWER(board_name)=LOWER('자유게시판'));

UPDATE boards SET is_default=TRUE
WHERE LOWER(board_name)=LOWER('자유게시판') AND is_default IS DISTINCT FROM TRUE;

CREATE TABLE IF NOT EXISTS comments (
    comment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT NOT NULL REFERENCES posts(post_id),
    author_member_id BIGINT NOT NULL REFERENCES members(member_id),
    body TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP
);

ALTER TABLE comments ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP;
CREATE INDEX IF NOT EXISTS idx_comments_post_active ON comments (post_id, created_at, comment_id) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_posts_board_active_latest ON posts (board_id, created_at DESC, post_id DESC) WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS post_images (
    image_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT NOT NULL REFERENCES posts(post_id),
    stored_name VARCHAR(255) NOT NULL,
    original_name VARCHAR(255) NOT NULL,
    content_type VARCHAR(50) NOT NULL,
    file_size INTEGER NOT NULL CHECK (file_size BETWEEN 1 AND 5242880),
    display_order SMALLINT NOT NULL DEFAULT 0 CHECK (display_order BETWEEN 0 AND 2),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_post_images_post ON post_images (post_id, display_order, image_id);

COMMIT;
