
from db_connect import get_connection

conn = get_connection()
cursor = conn.cursor()

# 모임
cursor.execute("""
CREATE TABLE IF NOT EXISTS recruits (
    recruit_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT NOT NULL UNIQUE,
    recruit_mode VARCHAR(20) NOT NULL,
    category VARCHAR(20) NOT NULL,
    capacity INT NOT NULL,
    meeting_datetime TIMESTAMP,
    place VARCHAR(255),
    is_online BOOLEAN,
    contact_method VARCHAR(255),
    deadline_at TIMESTAMP,
    state VARCHAR(20) NOT NULL,
    close_reason VARCHAR(30),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (post_id) REFERENCES posts(post_id)
)
""")

# 모임 참여자
cursor.execute("""
CREATE TABLE IF NOT EXISTS recruit_members (
    recruit_id BIGINT NOT NULL,
    member_id BIGINT NOT NULL,
    role VARCHAR(20),
    status VARCHAR(20),
    joined_at TIMESTAMP,
    canceled_at TIMESTAMP,
    updated_at TIMESTAMP,
    PRIMARY KEY (recruit_id, member_id),
    FOREIGN KEY (recruit_id) REFERENCES recruits(recruit_id),
    FOREIGN KEY (member_id) REFERENCES members(member_id)
)
""")

# 운동
cursor.execute("""
CREATE TABLE IF NOT EXISTS recruit_sports_details (
    recruit_id BIGINT PRIMARY KEY,
    sport_name VARCHAR(100),
    FOREIGN KEY (recruit_id) REFERENCES recruits(recruit_id)
)
""")

# 게임
cursor.execute("""
CREATE TABLE IF NOT EXISTS recruit_game_details (
    recruit_id BIGINT PRIMARY KEY,
    game_name VARCHAR(150),
    FOREIGN KEY (recruit_id) REFERENCES recruits(recruit_id)
)
""")

# 스터디
cursor.execute("""
CREATE TABLE IF NOT EXISTS recruit_study_details (
    recruit_id BIGINT PRIMARY KEY,
    study_topic VARCHAR(200),
    study_period VARCHAR(100),
    study_method VARCHAR(100),
    FOREIGN KEY (recruit_id) REFERENCES recruits(recruit_id)
)
""")

# 공동구매
cursor.execute("""
CREATE TABLE IF NOT EXISTS recruit_group_buy_details (
    recruit_id BIGINT PRIMARY KEY,
    product_name VARCHAR(200),
    purchase_url VARCHAR(500),
    estimated_price_per_person DECIMAL(10, 2),
    pickup_method VARCHAR(150),
    FOREIGN KEY (recruit_id) REFERENCES recruits(recruit_id)
)
""")

conn.commit()
cursor.close()
conn.close()

print("모임 관련 6개 테이블 생성 완료")
